#!/bin/sh

NAME="webadmin"
DIR="/opt/webadmin"
LOGFILE="/var/log/webadmin.log"
export PYTHONUNBUFFERED=1

start() {
    echo -n "Starting $NAME: "
    # Startet Python Flask im Hintergrund
    cd $DIR
    start-stop-daemon -S -b -m -p /var/run/$NAME.pid -O "$LOGFILE" --exec /usr/bin/python3 -- $DIR/app.py
    echo "OK"
}

stop() {
    echo -n "Stopping $NAME: "
    start-stop-daemon -K -q -p /var/run/$NAME.pid
    echo "OK"
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop; start ;;
    *) echo "Usage: $0 {start|stop|restart}"; exit 1 ;;
esac
